# Generated by Django 2.0.7 on 2018-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('object_type', models.CharField(choices=[('Q', 'Вопрос'), ('A', 'Ответ')], max_length=1, verbose_name='Тип лайкнутого обекта')),
                ('object_id', models.IntegerField(verbose_name='ID лайкнутого обекта')),
                ('like', models.IntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')])),
                ('date_of_change', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения решеняи')),
            ],
        ),
    ]
