# Generated by Django 2.0.7 on 2018-08-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_like', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_of_creation',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата создания'),
        ),
    ]
