# Generated by Django 2.0.7 on 2018-08-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_like', '0002_auto_20180819_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='user_like',
            field=models.IntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')], default=1),
        ),
    ]
