# Generated by Django 2.0.6 on 2018-06-04 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('about', models.TextField(default=None, max_length=256)),
                ('url_facebook', models.CharField(default=None, max_length=256)),
                ('url_vk', models.CharField(default=None, max_length=256)),
                ('url_twitter', models.CharField(default=None, max_length=256)),
                ('url_github', models.CharField(default=None, max_length=256)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('registration_date', models.DateField(default=datetime.datetime(2018, 6, 4, 22, 17, 44, 474284, tzinfo=utc))),
            ],
        ),
    ]
