# Generated by Django 2.0.6 on 2018-06-04 23:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 4, 23, 11, 55, 312133, tzinfo=utc)),
        ),
    ]
