# Generated by Django 2.0.6 on 2018-06-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_auto_20180605_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
