# Generated by Django 2.0.6 on 2018-06-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0003_auto_20180605_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url_facebook',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url_github',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url_twitter',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url_vk',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
