# Generated by Django 2.0.6 on 2018-06-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0006_auto_20180605_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
